[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyscitq2"
version = "0.1.0"
description = "Python DSL for defining scitq2 workflows"
authors = ["Raynald de Lahondès"]
readme = "README.md"
license = "MIT"
packages = [{ include = "scitq2", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.9"
grpcio = "^1.63.0"
grpcio-tools = "^1.63.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"