[project]
name = "pyscitq2"
version = "0.1.0"
description = "Python DSL for defining scitq2 workflows"
authors = [{ name="Raynald de Lahondès" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://github.com/gmtsciencedev/pyscitq2"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.poetry.dependencies]
python = ">=3.9"
grpcio = "^1.63.0"
grpcio-tools = "^1.63.0"  # if you're generating stubs from .proto

[tool.poetry.dev-dependencies]
pytest = "^8.2.0"